server:
    error:
        include-stacktrace: never
spring:
    datasource:
        password: ${MYSQL_PASSWORD}
        url: ${MYSQL_URL}?createDatabaseIfNotExist=true&serverTimezone=UTC
        username: ${MYSQL_USERNAME}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                jdbc:
                    lab:
                        non-contextual_creation: true
        show-sql: true
